mySQL:
  username: root
  password: abcd1234
  host: stock_market_data
  port: 3306
  database: stock_market

tuShare:
  host: http://api.tushare.pro
  token: f4f72ba37cebf3d93f5e632aaf96841fc547b94abe77be4d7d7dc34f